In [3]:
import numpy as np
from sklearn.cluster import KMeans
import pandas as pd

# New dataset with features 'Age', 'Salary', 'Years_of_Experience', 'Department', and 'Location'
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Age': [34, 45, 28, 39, 50, 42, 30, 29],
    'Salary': [55000, 70000, 45000, 60000, 75000, 65000, 48000, 43000],
    'Years_of_Experience': [5, 20, 3, 10, 25, 15, 4, 2],
    'Department': ['HR', 'Finance', 'IT', 'Sales', 'Marketing', 'IT', 'Finance', 'HR'],
    'Location': ['New York', 'Chicago', 'San Francisco', 'Austin', 'Los Angeles', 'Chicago', 'New York', 'Austin']
}

df = pd.DataFrame(data)

# Define features for clustering (use numeric features only)
X = df[['Age', 'Salary', 'Years_of_Experience']].values  # Excluding non-numeric columns

# Apply K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=42)  # Adjust number of clusters as needed
kmeans.fit(X)

# Add cluster labels to the dataframe
df['Cluster'] = kmeans.labels_

# Display the updated DataFrame with cluster labels
print(df)

# Display cluster centers
print("\nCluster Centers:")
print(kmeans.cluster_centers_)


   Employee_ID  Age  Salary  Years_of_Experience Department       Location  \
0          101   34   55000                    5         HR       New York   
1          102   45   70000                   20    Finance        Chicago   
2          103   28   45000                    3         IT  San Francisco   
3          104   39   60000                   10      Sales         Austin   
4          105   50   75000                   25  Marketing    Los Angeles   
5          106   42   65000                   15         IT        Chicago   
6          107   30   48000                    4    Finance       New York   
7          108   29   43000                    2         HR         Austin   

   Cluster  
0        2  
1        1  
2        0  
3        2  
4        1  
5        1  
6        0  
7        0  

Cluster Centers:
[[2.90000000e+01 4.53333333e+04 3.00000000e+00]
 [4.56666667e+01 7.00000000e+04 2.00000000e+01]
 [3.65000000e+01 5.75000000e+04 7.50000000e+00]]
